<?php class avaDesignModuleDefs {

	public static function product_hero_layout() {
		// product_hero
		return array (
			'key' => '57fb253f828e3',
			'name' => 'product_hero',
			'label' => 'Product/Services Hero',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_57fb25e3ec823',
					'label' => 'Product tagline',
					'name' => 'tag_line',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_57fb264aec824',
					'label' => 'Section Background',
					'name' => 'section_background',
					'type' => 'image',
					'instructions' => 'If no image is added, the standard image will be used. min 960w x 440h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_57fb264aec825',
					'label' => 'Desktop Background 1440 X 410',
					'name' => 'section_background_1440_410',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_57fb264aec826',
					'label' => 'Medium Background 992 X 410',
					'name' => 'section_background_992_410',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_57fb264aec827',
					'label' => 'Small Background 768 X 570',
					'name' => 'section_background_768_570',
					'type' => 'image',
					'instructions' => 'Min 570h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '570',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_57fb264aec828',
					'label' => 'Extra Small Background 480 X 645',
					'name' => 'section_background_480_645',
					'type' => 'image',
					'instructions' => 'Min 645h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '645',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	public static function product_description_layout() {
		return array (
			'key' => '58066e0a194e6',
			'name' => 'product_description',
			'label' => 'WYSIWYG Description',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58066e9bb4df5',
					'label' => 'WYSIWYG Description',
					'name' => 'product_desc',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	// product_features
	public static function product_features_layout() {
		return array (
			'key' => '58006b62b891d',
			'name' => 'product_features',
			'label' => 'Product Features',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58007290b891e',
					'label' => 'Feature Statements',
					'name' => 'feature_statements',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 1,
					'max' => 3,
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_58015545555d2',
							'label' => 'Product Feature Title',
							'name' => 'feature_title_left',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58007436e5365',
							'label' => 'Product Feature Description',
							'name' => 'feature_description_left',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58069d9944217',
							'label' => 'Product Feature Title',
							'name' => 'feature_title_right',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58069db544218',
							'label' => 'Product Feature Description',
							'name' => 'feature_description_right',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	// product_video
	public static function product_video_layout() {
		return array (
			'key' => '58013b6842ed9',
			'name' => 'product_video',
			'label' => 'Product Video',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5822904143044',
					'label' => 'Video Preview Size',
					'name' => 'video_preview_size',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'small' => 'Small',
						'medium' => 'Medium',
						'large' => 'Large',
					),
					'default_value' => array (
						0 => 'Small',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58013bba42edb',
					'label' => 'Video Title',
					'name' => 'video_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58013b8d42eda',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'width' => 360,
					'height' => 220,
				),
				array (
					'key' => 'field_58013bdd42edc',
					'label' => 'Video Description',
					'name' => 'video_description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	// textbar
	public static function product_textbar_layout() {
		return array (
		'key' => '5859a00b531c3',
		'name' => 'product_textbar',
		'label' => 'Textbar',
		'display' => 'block',
		'sub_fields' => array (
			array (
				'key' => 'field_5859a015531c4',
				'label' => 'Left Text',
				'name' => 'left_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5859a024531c5',
				'label' => 'Right Text',
				'name' => 'right_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_588fb440aeaf1',
				'label' => 'File',
				'name' => 'file',
				'type' => 'file',
				'instructions' => 'Link to the PDF to display when clicked',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'min' => '',
		'max' => '',
		);
	}

	// whitepaper hero
	public static function whitepaper_hero_layout() {
		return array (
			'key' => '581b72a26fc45',
			'name' => 'whitepaper_hero',
			'label' => 'Whitepaper hero',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_581b72a26fc48',
					'label' => 'Hero Image',
					'name' => 'hero_image',
					'type' => 'image',
					'instructions' => '750w x 200h image. Section will use the standard whitepaper image if none is specified.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	// home page hero
	public static function home_page_hero_layout() {
		return array (
			'key' => '5835a928353d4',
			'name' => 'home_page_hero',
			'label' => 'Home Page Hero',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58928249e64e4',
					'label' => 'Template to use',
					'name' => 'template_to_use',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Shortcode' => 'Shortcode',
						'Internal' => 'Internal',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_58927f09e64e2',
					'label' => 'Hero Shortcode',
					'name' => 'hero_shortcode',
					'type' => 'text',
					'instructions' => 'Avalara Hero Banner shortcode in the form [avalaraHeroBanner]',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '==',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5835a98f32433',
					'label' => 'Hero Text',
					'name' => 'hero_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5835a9c432434',
					'label' => 'Hero Button Label',
					'name' => 'hero_button_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5840eacba2470',
					'label' => 'Hero Image 480 X 645',
					'name' => 'hero_image_768',
					'type' => 'image',
					'instructions' => 'Min 645h image',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '645',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5835a9d532435',
					'label' => 'Hero Image 768 X 570',
					'name' => 'hero_image_1000',
					'type' => 'image',
					'instructions' => 'Min 570h image',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '570',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5840eac9a246f',
					'label' => 'Hero Image 992 X 410',
					'name' => 'hero_image_1200',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5840eac7a246e',
					'label' => 'Hero Image 1440 X 410',
					'name' => 'hero_image_1400',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58672390d1e69',
					'label' => 'Hero Text Color',
					'name' => 'hero_text_color',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58928249e64e4',
								'operator' => '!=',
								'value' => 'Shortcode',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'light' => 'Light',
						'dark' => 'Dark',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'Light',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	// home page value prop
	public static function home_page_value_prop_layout() {
		return array (
			'key' => '5835aa25aa3a2',
			'name' => 'home_page_value_prop',
			'label' => 'Home Page Value Prop',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5835aa4caa3a3',
					'label' => 'Headline',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5840fbf288b19',
					'label' => 'Main Body',
					'name' => 'main_body',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_5835aabdaa3a7',
					'label' => 'Box Title',
					'name' => 'box_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5835aa80aa3a5',
					'label' => 'Secondary Headline',
					'name' => 'secondary_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5835aa8daa3a6',
					'label' => 'Secondary Description',
					'name' => 'secondary_description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				//Select the URL type, viz internal or external
				array (
					'key' => 'field_58c11f1a329b9',
					'label' => 'Hyperlink for \'Learn more\'',
					'name' => 'learn_more_link_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Internal' => 'Internal',
						'External' => 'External',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'Internal',//default to internal url
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				//default internal url
				array (
					'key' => 'field_5835aae6aa3a8',
					'label' => 'Select Page',
					'name' => 'learn_more_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58c11f1a329b9',
								'operator' => '==',
								'value' => 'Internal',
							),//check the condition
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				//external link field
				array (
					'key' => 'field_58c11fe1329ba',
					'label' => 'External Link',
					'name' => 'external_link',
					'type' => 'text',
					'instructions' => 'Please add http:// or https:// before URL',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_58c11f1a329b9',
								'operator' => '==',
								'value' => 'External',
							),//check the condition
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'http://www.avalara.com',//to show the standardformat for url
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	// home page product services
	public static function home_page_prod_svcs_layout() {
		return array (
			'key' => '5835ad75714ae',
			'name' => 'product_services_grid',
			'label' => 'Product Services Grid',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5835ad95714af',
					'label' => 'Categories',
					'name' => 'categories',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_5835add1714b0',
							'label' => 'Category Name',
							'name' => 'category_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5835adec714b1',
							'label' => 'Pages',
							'name' => 'pages',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Box',
							'sub_fields' => array (
								array (
									'key' => 'field_5835ae0d714b2',
									'label' => 'page link',
									'name' => 'page_link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
								array (
									'key' => 'field_5835affd66660',
									'label' => 'Title Override',
									'name' => 'title_override',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5835b00f66661',
									'label' => 'Description Override',
									'name' => 'description_override',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => '',
								),
							),
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	// partners page
	public static function partners_page_layout() {
		return array (
			'key' => '5847407fe1c5b',
			'name' => 'partners_page',
			'label' => 'Partners Page',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58474091e1c5c',
					'label' => 'Section Background',
					'name' => 'section_background',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58477d7ed5ef2',
					'label' => 'Desktop Background 1440 X 410',
					'name' => 'partner_section_background_desktop',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58477d7ed5ef3',
					'label' => 'Medium Background 992 X 410',
					'name' => 'partner_section_background_medium',
					'type' => 'image',
					'instructions' => 'Min 410h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '410',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58477d7ed5ef4',
					'label' => 'Small Background 768 X 570',
					'name' => 'partner_section_background_small',
					'type' => 'image',
					'instructions' => 'Min 570h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '570',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58477d7ed5ef5',
					'label' => 'Extra Small Background 480 X 645',
					'name' => 'partner_section_background_extra_small',
					'type' => 'image',
					'instructions' => 'Min 645h image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '645',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_584740f5e1c5d',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58474102e1c5e',
					'label' => 'Detail Text',
					'name' => 'detail_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_5847412ee1c5f',
					'label' => 'Program Boxes Title',
					'name' => 'program_boxes_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847414ee1c60',
					'label' => 'Program Boxes',
					'name' => 'program_boxes',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_58474163e1c61',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5847416de1c62',
							'label' => 'Detail Text',
							'name' => 'detail_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5847417be1c63',
							'label' => 'Link Title Text',
							'name' => 'link_title_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Sign Up Now',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58474198e1c64',
							'label' => 'Link',
							'name' => 'link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array (
					'key' => 'field_58477d64d5ef0',
					'label' => 'Partner Image Title',
					'name' => 'partner_image_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58477d7ed5ef1',
					'label' => 'Partner Image',
					'name' => 'partner_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}

	public static function thank_you_layout() {
		return array (
			'key' => '58479b8a6604f',
			'name' => 'thank_you_page',
			'label' => 'Thank You Page',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58479bcf66050',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58479bde66051',
					'label' => 'CTA Button Text',
					'name' => 'cta_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58479bec66052',
					'label' => 'CTA Button Link',
					'name' => 'cta_button_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array (
					'key' => 'field_58479bf766053',
					'label' => 'Home Page Link Text',
					'name' => 'home_page_link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58479c0966054',
					'label' => 'Home Page Link',
					'name' => 'home_page_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
				array (
					'key' => 'field_5847a85c1b240',
					'label' => 'Whiteboard Text',
					'name' => 'whiteboard_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847a8681b241',
					'label' => 'Whiteboard Video',
					'name' => 'whiteboard_video',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function contact_layout() {
		return array (
			'key' => '5847c6b3ddb09',
			'name' => 'contact_page',
			'label' => 'Contact Page',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5847c6bcddb0a',
					'label' => 'Phone Label',
					'name' => 'phone_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847c6c9ddb0b',
					'label' => 'Phone Number',
					'name' => 'phone_number',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				//adding a new fields for secondary contact number
				array (
					'key' => 'field_5847c6bsecno1',
					'label' => 'Phone Label',
					'name' => 'phone_label_2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847c6bsecno2',
					'label' => 'Phone Number',
					'name' => 'phone_number_2',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847c6d2ddb0c',
					'label' => 'Address',
					'name' => 'address',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
				),
				array (
					'key' => 'field_5847c6e1ddb0d',
					'label' => 'map',
					'name' => 'map',
					'type' => 'textarea',
					'instructions' => 'Embed a map or directions
	To embed a map or directions in a website or blog, follow the steps below.

	Open Google Maps. https://www.google.com/maps
	Make sure the map, Street View image, or directions you\'d like to embed shows up on the map.
	In the top left corner, click the Menu .
	Click Share or Embed map.
	At the top of the box that appears, choose Embed map.
	Choose the size you want, then copy the HTML embed code and paste it into the source code of your website or blog.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function about_layout() {
		return array (
			'key' => '5847f136f3de6',
			'name' => 'about_page',
			'label' => 'About Page',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5847f4b6d50cc',
					'label' => 'Section Background',
					'name' => 'section_background',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_588fe2543b928',
					'label' => 'Section Background Mobile',
					'name' => 'section_background_mobile',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5847f13ff3de7',
					'label' => 'Final Text',
					'name' => 'final_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_5847f154f3de8',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5847f15df3de9',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function testimonial_hero_banner() {
		return array (
			'key' => '58be331907dd0',
			'name' => 'testimonial_hero_banner',
			'label' => 'Testimonial Hero Banner',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58be38e6d6cb1',
					'label' => 'Headline',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58be38ecd6cb2',
					'label' => 'Hero Image Large',
					'name' => 'hero_image_large',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58be3915d6cb3',
					'label' => 'Hero Image Medium',
					'name' => 'hero_image_medium',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58be3927d6cb4',
					'label' => 'Hero Image Small',
					'name' => 'hero_image_small',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_58be3935d6cb5',
					'label' => 'Hero Image Extra Small',
					'name' => 'hero_image_extra_small',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function testimonial_hero_quote() {
		return 	array (
			'key' => '58be332707dd1',
			'name' => 'testimonial_hero_quote',
			'label' => 'Testimonial Hero Quote',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58be379c37f52',
					'label' => 'Quote',
					'name' => 'quote',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_58be37b137f53',
					'label' => 'Quote Attribution Name and Location',
					'name' => 'quote_attribution_name_and_location',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function testimonial_quote_boxes() {
		return array (
			'key' => '58be334907dd2',
			'name' => 'testimonial_quote_boxes',
			'label' => 'Testimonial Quote Boxes',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58be34898f87d',
					'label' => 'Quote Box',
					'name' => 'quote_box',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_58be34a48f87e',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => 'attribution name for quote',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Name',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58be34f78f87f',
							'label' => 'Location',
							'name' => 'location',
							'type' => 'text',
							'instructions' => 'City, St or location of the one quoted',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58be35298f880',
							'label' => 'Quote',
							'name' => 'quote',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_58cfea05c35ac',
							'label' => 'Image or Video',
							'name' => 'image_or_video',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'None' => 'None',
								'Image' => 'Image',
								'Video' => 'Video',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'None',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_58cfea57c35ad',
							'label' => 'image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_58cfea05c35ac',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_58cfea75c35ae',
							'label' => 'video',
							'name' => 'video',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_58cfea05c35ac',
										'operator' => '==',
										'value' => 'Video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => 91,
							'height' => 91,
						),
					),
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function testimonial_feature_quote() {
		return array (
			'key' => '58be336c07dd3',
			'name' => 'testimonial_feature_quote',
			'label' => 'Testimonial Feature Quote',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58be3580d4388',
					'label' => 'Quote Background Color',
					'name' => 'quote_background_color',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'light' => 'light',
						'dark' => 'dark',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_58c9110d6e050',
					'label' => 'Quote Image Left Right',
					'name' => 'quote_image_left_right',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Left' => 'left',
						'Right' => 'right',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'right',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_58be3635d438a',
					'label' => 'Quote',
					'name' => 'quote',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_58be35d3d4389',
					'label' => 'Quote Attribution Name and Location',
					'name' => 'quote_attribution_name_and_location',
					'type' => 'text',
					'instructions' => 'Follows the Quote. All of the text after the dash ("-"), i.e. "Andy, Stonington, ME" for the attribution line "- Andy, Stonington, ME"',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58be36bcd438b',
					'label' => 'Feature Image',
					'name' => 'feature_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
	public static function testimonial_cta() {
		return array (
			'key' => '58be338a07dd4',
			'name' => 'testimonial_cta',
			'label' => 'Testimonial CTA',
			'display' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_58be36fab88f1',
					'label' => 'Headline',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58c0c9546ce06',
					'label' => 'Left Headline',
					'name' => 'left_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58be3709b88f2',
					'label' => 'Left Detail',
					'name' => 'left_detail',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_58c0c97d6ce07',
					'label' => 'Left CTA',
					'name' => 'left_cta',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58c0cd276ce08',
					'label' => 'Middle Headline',
					'name' => 'middle_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58be3762b88f3',
					'label' => 'Middle Detail',
					'name' => 'middle_detail',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_58c0cd3b6ce09',
					'label' => 'Middle Button Text',
					'name' => 'middle_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58c0cd576ce0a',
					'label' => 'Middle Button Link',
					'name' => 'middle_button_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_58c0cdbc6ce0b',
					'label' => 'Right Headline',
					'name' => 'right_headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58be3778b88f4',
					'label' => 'Right Detail',
					'name' => 'right_detail',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58c0cdd36ce0c',
					'label' => 'Right Button Text',
					'name' => 'right_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_58c0cde36ce0d',
					'label' => 'Right Button Link',
					'name' => 'right_button_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
			'min' => '',
			'max' => '',
		);
	}
}